version: "3.8"
services:
  consul:
    image: progrium/consul
    command: -server -bootstrap
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
